### ISSUE TITLE
Getting location from Android app and update the admin panel

### ISSUE THREAD

**Issue by chanakaDe** [jameshiew/simple-chat-websockets#1]
Hello Buddy,
I'm Chanaka from Sri Lanka.
I'm creating an Android application to send current location via GPS data and display the location in Admin panel. I have a server written in Node.JS. Admin panel is written using AngularJS.

How can I use your code to work on that ? I'm totally new to socket.io and no good knowledge on that. 
Simple user send a request from Admin panel by selecting the device. Then Device need to send me back GPS location.

![screenshot from 2018-07-20 17-18-40](https://user-images.githubusercontent.com/7803591/43001035-6b113d52-8c41-11e8-9a91-d2167946ed8e.png)

This is how i'm going to show that. Please help me on this. My university project :+1: @jameshiew

**Comment by jameshiew** [comment]
Hey Chanaka, this is just a repo to hold the example code for a specific stackoverflow.com question - the code herein would probably not be all that useful to you. Your best bet would be to ask for advice over at https://stackoverflow.com - you can tag your question with the `sockets.io` tag. Best of luck with your project!
